---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  vars:
    pip_packages:
      - "cryptography"
      - "bcrypt"
    packages_debian:
      - "openssh-client"
    packages_redhat:
      - "openssh-clients"
    users_groups:
      - name: "test1"
      - name: "test2"

    users:
      - name: "test1"
        group: "test1"
      - name: "test2"
        group: "test2"

  roles:
    - name: mullholland.repository_epel
    - name: mullholland.packages
    - name: mullholland.pip
    - name: mullholland.users
