---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    generation:
      - user: "test1"
        path: "/home/test1/.ssh/id_rsa"
      - user: "test1"
        path: "/home/test1/.ssh/id_dsa"
      - user: "test1"
        path: "/home/test1/.ssh/id_ecdsa"
      - user: "test1"
        path: "/home/test1/.ssh/id_ed25519"
      - user: "test2"
        path: "/home/test2/.ssh/id_rsa"

    copy_keys:
      - user: "test1"
        path: "/home/test1/.ssh/id_custom"
      - user: "test1"
        path: "/home/test1/.ssh/id_custom2"
      - user: "test1"
        path: "/home/test1/.ssh/id_custom3"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

#######################################
# check generation
#######################################

    - name: check generated ssh key pairs
      ansible.builtin.lineinfile:
        name: "{{ item.path }}"
        line: "-----BEGIN OPENSSH PRIVATE KEY-----"
        state: present
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: "0600"
      check_mode: true
      register: generation_hcl
      failed_when: (generation_hcl is changed) or (generation_hcl is failed)
      with_items: "{{ generation }}"

#######################################
# check copy
#######################################

    - name: check copied ssh key pairs
      ansible.builtin.lineinfile:
        name: "{{ item.path }}"
        line: "-----BEGIN OPENSSH PRIVATE KEY-----"
        state: present
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: "0600"
      check_mode: true
      register: copy_hcl
      failed_when: (copy_hcl is changed) or (copy_hcl is failed)
      with_items: "{{ copy_keys }}"

#######################################
# authorized_keys
#######################################

    - name: check authorized_keys file
      ansible.builtin.lineinfile:
        name: "/home/test1/.ssh/authorized_keys"
        line: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGRjjIGC9+IuHJGTj9Uza95w1ftFJaWsE3JRFU0pnY55 test@key1"
        state: present
        owner: "test1"
        group: "test1"
        mode: "0600"
      check_mode: true
      register: authorized_hcl
      failed_when: (authorized_hcl is changed) or (authorized_hcl is failed)
